apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-image
  template:
    metadata:
      labels:
        app: postgres-image
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: postgres-image
        image: postgres
        ports:
        #TODO: Alterar port para o esperado pelo Postgres
	# usar o 8080 necessita de uma config extra para mudar o port da imagem para 8080 (POSTGRES_PORT = 8080)
        - containerPort: 5432 # trying with 5432 default postgres port
        env:
        #TODO: Replace with Kubernetes Secret (optional)
        - name: POSTGRES_USER
          value: postgres
          # valueFrom:
          #   secretKeyRef:
          #     name: postgres-secrets
          #     key: postgres-user
        - name: POSTGRES_PASSWORD
          value: postgres
          # valueFrom:
          #   secretKeyRef:
          #     name: postgres-secrets
          #     key: postgres-password
        - name: POSTGRES_DB
          value: tukano
        resources:
          requests:
            cpu: 1m
            memory: 50Mi
          limits:
            cpu: 75m
            memory: 128Mi
        startupProbe:
          tcpSocket:
            #path: /health
            port: 5432
          failureThreshold: 5
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            #path: /health
            port: 5432
          failureThreshold: 3
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            #path: /health
            port: 5432
          failureThreshold: 5
          initialDelaySeconds: 3
          periodSeconds: 3
