apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-image
  template:
    metadata:
      labels:
        app: postgres-image
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: postgres-image
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: tukano
        resources:
          requests:
            cpu: 1m
            memory: 50Mi
          limits:
            cpu: 75m
            memory: 128Mi
        startupProbe:
          tcpSocket:
            port: 5432
          failureThreshold: 5
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 5432
          failureThreshold: 3
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 5432
          failureThreshold: 5
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5432
    targetPort: 5432
  selector:
    app: postgres-image
