apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-image
  template:
    metadata:
      labels:
        app: redis-image
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: redis-image
        image: redis
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 1m
            memory: 50Mi
          limits:
            cpu: 75m
            memory: 128Mi
        startupProbe:
          tcpSocket:
            #path: /health
            port: 6379
          failureThreshold: 5
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            #path: /health
            port: 6379
          failureThreshold: 3
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            #path: /health
            port: 6379
          failureThreshold: 5
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: redis-image
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 6379
    targetPort: 6379
  selector:
    app: redis-image
