apiVersion: apps/v1
kind: Deployment
metadata:
  name: blob-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blob-image
  template:
    metadata:
      labels:
        app: blob-image
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: blob-image
        image: hemareso/blob-storage
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            cpu: 75m
            memory: 512Mi
        startupProbe:
          httpGet:
            path: blob-storage/rest/health
            port: 8080
          failureThreshold: 10
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: blob-storage/rest/health
            port: 8080
          failureThreshold: 3
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: blob-storage/rest/health
            port: 8080
          failureThreshold: 5
          initialDelaySeconds: 3
          periodSeconds: 3
