apiVersion: v1
kind: PersistentVolume
metadata:
  name: blob-persistent-volume
spec:
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mnt/blobs
  capacity:
    storage: 2Gi
  storageClassName: ""
  volumeMode: Filesystem
