apiVersion: apps/v1
kind: Deployment
metadata:
  name: tukano-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tukano-image
  template:
    metadata:
      labels:
        app: tukano-image
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: tukano-image
      #TODO: Create tukano image and upload to DockerHub
        image: hemareso/tukano-server:latest
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_URL
          value: "redis-service"
        # - name: KUBERNETES_CLUSTER_DNS
        #   value: #TODO: Get DNS from Azure cluster
        resources:
          requests:
            cpu: 5m
            memory: 128Mi
          limits:
            cpu: 75m
            memory: 512Mi
        startupProbe:
          httpGet:
            path: tukano/rest/health
            port: 8080
          failureThreshold: 10
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: tukano/rest/health
            port: 8080
          failureThreshold: 3
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: tukano/rest/health
            port: 8080
          failureThreshold: 5
          initialDelaySeconds: 3
          periodSeconds: 3
      initContainers:
      - name: wait-for-postgres
        image: busybox
        command: ['sh', '-c', 'until nc -zv postgres-image 5432; do echo waiting for postgres-image; sleep 2; done;']
        resources:
          requests:
            cpu: 1m
            memory: 50Mi
          limits:
            cpu: 75m
            memory: 128Mi    
      - name: wait-for-redis
        image: busybox
        command: ['sh', '-c', 'until nc -zv redis-image 6379; do echo waiting for redis-image; sleep 2; done;']
        resources:
          requests:
            cpu: 1m
            memory: 50Mi
          limits:
            cpu: 75m
            memory: 128Mi
